### ISSUE TITLE
an issue with delfem2::CCad2D

### ISSUE THREAD

**Issue by stnoh** [nobuyuki83/delfem2#88] opened 2021-11-01 12:57 UTC
Hello, I found a small issue with `delfem2::CCad2D`. I tested my input on the example code below:
https://github.com/nobuyuki83/delfem2/blob/master/examples_newgl_glfw/30_cadmsh2d/main.cpp

Here is the minimum sample input for the constructor:
```C++
CCadDtri_Viewer() {
  std::vector<double> aXY = {
    -0.84, +1.20,
    -1.00, +0.25,
    -1.00, -1.40,
    +1.00, -1.40,
    +1.00, +0.25,
    +0.84, +1.20,
    +0.30, +1.40,
    -0.30, +1.40
  };
  cad.AddPolygon(aXY);
  
  #if 1
  // sleeve (R)
  {
    double param[4] = { 0.25, -0.15, 0.5, -0.25 };
    std::vector<double> vparam(param, param + 4);
    cad.SetEdgeType(0, delfem2::CCad2D_EdgeGeo::BEZIER_CUBIC, vparam);
  }
  
  // sleeve (L)
  {
    double param[4] = { 0.25, -0.15, 0.5, -0.25 };
    std::vector<double> vparam(param, param + 4);
    cad.SetEdgeType(4, delfem2::CCad2D_EdgeGeo::BEZIER_CUBIC, vparam);
  }
  
  // neck
  {
    double param[4] = { 0.0, 0.0, 0.5, -1.0 };
    std::vector<double> vparam(param, param + 4);
    cad.SetEdgeType(6, delfem2::CCad2D_EdgeGeo::BEZIER_CUBIC, vparam);
  }
  #endif
}
```

If I drag a point or edge of the input, the mesh breaks down if I keep using the bottom part (from `#if 1` to `#endif`).
Moreover, when I change `delfem2::CCad2D_EdgeGeo::BEZIER_CUBIC` to `delfem2::CCad2D_EdgeGeo::BEZIER_QUADRATIC`, the program cannot pick the drag-and-drop points properly.
However, the program seems to work appropriately when I comment out the bottom part.

Do you have any suggestions to fix the problem?

**Comment by nobuyuki83** [comment] 2021-11-04 02:28
![Screen Shot 2021-11-04 at 11 17 36 AM](https://user-images.githubusercontent.com/40525402/140247538-170c0abf-1038-4cfe-9e45-52b5faa51e11.png)
![Screen Shot 2021-11-04 at 11 17 43 AM](https://user-images.githubusercontent.com/40525402/140247543-fa022e06-c8b4-480e-bf69-444d669981ae.png)

**Comment by nobuyuki83** [comment] 2021-11-04 06:31
This line of code is the cause of the problem.
`    double param[4] = { 0.0, 0.0, 0.5, -1.0 };`

The parameter should not be {0.0, 0.0, *, *} or {*, *, 0.0, 0.0} otherwise there will be zero division for all the vertex when computing the mean value coordinate.

**Comment by stnoh** [comment] 2021-11-04 06:46
Well, I see... 
After changing the {0.0, 0.0} part, I do not encounter such a broken mesh, but the mesh has still issues, such as:
- edges of the mesh do not perfectly match the Bezier line (both QUADRATIC and CUBIC)
- some vertices in the mesh go outside of mesh, when dragging the point/edge (usually happens at CUBIC)

Are these the expected result?

**Comment by stnoh** [comment] 2021-11-04 06:54
Here is the situation I encountered:
![image](https://user-images.githubusercontent.com/9264664/140270240-5daf691d-454e-4250-ad25-36b218f02ede.png)
![image](https://user-images.githubusercontent.com/9264664/140270261-0c8cc68f-9f6f-4741-abfb-99d01345860f.png)

**Comment by nobuyuki83** [comment] 2021-11-04 07:25
Currently, I'm using the Mean Value Coordinate (MVC) for the mesh morphing. Thus, it is difficult to handle concave shapes using MVC.  There seems to be no easy way to fix this issue.  I will try to write the code to handle concave shapes when I have time. I keep this issue open.

**Comment by nobuyuki83** [comment] 2021-11-06 12:23
![Uploading Hnet.com-image.gif…]()

**Comment by nobuyuki83** [comment] 2021-11-07 01:33
I fixed the problem and committed the update in https://github.com/nobuyuki83/delfem2/commit/a51131190bf483976c9c3e4f7fb7a1773e4b3e73

![Screen Shot 2021-11-07 at 10 25 13 AM](https://user-images.githubusercontent.com/40525402/140628873-cf4a964a-56b2-4c63-97c0-5cf892065121.png)

Check out the new `30_cadmsh2d` demo:
https://github.com/nobuyuki83/delfem2/tree/master/examples_newgl_glfw/30_cadmsh2d

**Comment by nobuyuki83** [comment] 2021-11-16 04:49
I assume this issue is solved. Otherwise please reopen this issue.

**Closed by nobuyuki83** 2021-11-16 04:49 UTC
